
[[ $- != *i* ]] && return

export LANG=en_US.utf8
export NNTPSERVER="news.epita.fr"

#export EDITOR=vim

alias ls='ls --color=auto'
PS1='[\u@\h \W]\$ '

alias clr='clear'

alias importmakefile='cp ~/afs/Script/Makefile .'

source ~/afs/Script/fancy_lock.sh 
